name: dotnet-build

# run on both branch push and tag push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - run: dotnet build ./src/StringSpan/StringSpan.csproj -c Debug
      - run: dotnet test ./src/StringSpanUnitTests/StringSpanUnitTests.csproj -c Debug

  benchmark:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - run: dotnet restore ./src/Benchmark/Benchmark.csproj
      - run: dotnet run --project ./src/Benchmark/Benchmark.csproj -c Release --filter ** --join
